###

GET http://localhost:4897 HTTP/1.1

###

GET http://localhost:4897/a68b823c-7ca6-44bc-b721-fb4d5312cafc HTTP/1.1

### CREATE USER
# walexeniola081@gmail.com
# oluwatomiwa96@gmail.com
# kennetholuwatomiwa966@gmail.com
POST http://localhost:4897/register HTTP/1.1
content-type: application/json

{
    "email": "oluwatomiwa96@gmail.com",    
    "password": "hashpassowrd",
    "firstName": "Lola",
    "lastName" : "Philips",
    "phoneNumber": "+2347014216076"
}

### VERIFY USER

POST http://localhost:4897/verify HTTP/1.1
content-type: application/json

{
    "email": "oluwatomiwa96@gmail.com",    
    "otp": "6536"
}

### LOGIN USER
POST http://localhost:4897/login HTTP/1.1
content-type: application/json

{
   "email": "oluwatomiwa96@gmail.com",
    "password": "hashpasowrd"
}

### GET MY PROFILE
GET http://localhost:4897/my-profile HTTP/1.1
Content-Type: application/xml
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzQyMGNlZTVhZjY5NWE0ZTI0MzQyYSIsImVtYWlsIjoib2x1d2F0b21pd2E5NkBnbWFpbC5jb20iLCJpYXQiOjE2ODUzMzQ0MzUsImV4cCI6MTY4NTQyMDgzNX0.LZyYpSI96HpF3q0Gn3fPO2YZONLslOS60Bbawsh9uUY

### UPDATE USER

PUT http://localhost:4897/update/a68b823c-7ca6-44bc-b721-fb4d5312cafc HTTP/1.1
content-type: application/json

{
    "name": "Topklass",
    "email": "walexeniola081@gmail.com",
    "age": 57
}

### REMOVE USER

POST http://localhost:4897/remove/a68b823c-7ca6-44bc-b721-fb4d5312cafc HTTP/1.1
content-type: application/json
 

### RESEND OTP

POST http://localhost:4897/resend-otp HTTP/1.1
content-type: application/json

{
    "email": "oluwatomiwa96@gmail.com"
}